### ISSUE TITLE
wrong arXiv reference in readme.md

### ISSUE THREAD

**Issue by gabella** [vallis/truebayes#1]
I see that the arXiv number for Chua et al. is not correct in the readme.md.  The correct number is 1909.05966v2 (I am looking at it on my desk...and Stephen Taylor from the other reference is now down the hall, so it was good to learn that reference too:).

Just an FYI, not high priority, bill gabella (Vanderbilt)

**Comment by alvincjk** [comment]
Thank you for the heads-up, Bill! It's fixed now.
